# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MeetTheTeam' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Object Mapper - JSON Reader
  pod 'ObjectMapper', '~> 2.2'

  target 'MeetTheTeamTests' do
    inherit! :search_paths
    pod 'ObjectMapper', '~> 2.2'
  end

  target 'MeetTheTeamUITests' do
    inherit! :search_paths
    pod 'ObjectMapper', '~> 2.2'
  end

end
